server:
  port: 54001
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  rabbitmq: #rabbitmq相关配置
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.perperon.mall.pojo
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: perperon-service-web #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: perperon
  key:
    admin: 'web:admin'
    token: 'web:jwt'
  expire:
    common: 86400 # 24小时

pagehelper:
  helperDialect: mysql # 数据库方言
  reasonable: true # 支持接口参数中的pageNum和pageSize为0时查询第一页记录
  supportMethodsArguments: true # 支持通过 Mapper 接口参数来传递分页参数
  #params: count=countSql # 分页参数名
  offsetAsPageNum: true # 使用 RowBounds 分页时，将参数 offset 作为 pageNum 查询
  rowBoundsWithCount: true # 使用 RowBounds 进行分页时是否查询总记录数

#feign:
#  okhttp:
#    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic

secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/actuator/**"