server:
  port: 8001
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，使用微服务名
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: perperon-service-web
          uri: lb://perperon-service-web
          predicates:
            - Path=/service-web/**
          filters:
            - StripPrefix=1
        - id: baidu-test
          uri: http://news.baidu.com
          predicates:
            - Path=/guonei
#          filters:
#            - StripPrefix=1
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

